startup_progs = ["xrandr --output DP-2 --mode 2560x1440 --rate 144.00 --primary --output DP-0 --mode 1920x1080 --rate 75.00 --right-of DP-2 --rotate left", "nitrogen --restore", "picom --daemon"]
log_level = "warning"
workspaces = [
  "web",
  "code",
  "banana"
]

[gaps]
outer = 30
inner = 20

[border]
width = 3

[keybindings]
"Super+e" = { action = "spawn", value = "kitty -o allow_remote_control=yes -o enabled_layouts=tall,stack", desc = "Launch Terminal" }
"Super+space" = { action = "spawn", value = "rofi -show drun -theme ~/.config/rofi/launcher.rasi", desc = "Launch Applications" }

"Super+q" = { action = "killclient", desc = "Kill current window" }
"Super+r" = { action = "reload", desc = "Reload configuration" }
"Super+f" = { action = "togglefloating", desc = "Toggle floating mode" }
"Super+Escape" = { action = "cyclefocus", desc = "Cycle focus" }

"Super+l" = { action = "focusmonitor", value = "right", desc = "Focus right monitor" }
"Super+h" = { action = "focusmonitor", value = "left", desc = "Focus left monitor" }
"Super+Shift+l" = { action = "movetomonitor", value = "right", desc = "Move window to right monitor" }
"Super+Shift+h" = { action = "movetomonitor", value = "left", desc = "Move window to left monitor" }

"Super+1" = { action = "viewworkspace", value = "web", desc = "View web workspace" }
"Super+2" = { action = "viewworkspace", value = "code", desc = "View code workspace" }
"Super+3" = { action = "viewworkspace", value = "banana", desc = "View banana workspace" }

"Super+Shift+1" = { action = "movetoworkspace", value = "web", desc = "Move window to web workspace" }
"Super+Shift+2" = { action = "movetoworkspace", value = "code", desc = "Move window to code workspace" }
"Super+Shift+3" = { action = "movetoworkspace", value = "banana", desc = "Move window to banana workspace" }
