name: C CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libx11-dev libxft-dev libxinerama-dev git

      - name: Build AtlasWM
        run: make
      - name: Clean
        run: make clean
